### ISSUE TITLE
How long does it take to run on a single gpu?

### ISSUE THREAD

**Issue by whaleloops** [MiuLab/PLM-ICD#1]
How long does it take to run on a single GPU with 8 batch size according to your paper? It is estimating me 4 days? Any recommendations to speed up the process?

**Comment by chaoweihuang** [comment]
Hi,

Thank you for your interest in our work!
With the parameters provided in the README, the training process took around 12 hours to run using a single 2080Ti.
I would recommend:
1. Use FP16 training if it's compatible with your GPU.
2. Reducing num_train_epochs to 12 leads to similar performance in my experience.

Chao-Wei
