### ISSUE TITLE
Trained model does not saved

### ISSUE THREAD

**Issue by LeiGong0125Carrot** [MiuLab/PLM-ICD#10]
Hello authors, this is a great work. I am trying to train the model based on the MIMIC-IV datasets, initially using epoch = 2, however, the trained model is not saved, could you help me figure this out?

**Comment by chaoweihuang** [comment]
Hi @LeiGong0125Carrot 

Please set the `--output_dir` argument to the path where you'd like to save your model.
If you used the command listed in our README, then the trained will be saved in `../models/`

Chao-Wei

**Comment by LWserenic** [comment]
Hello @LeiGong0125Carrot, I also want to train the model based on MIMIC-IV datasets but encounter a problem about KeyError:"label_ids". Do you encounter it too? Or how do you preprocess the dataset? Thank you in advance.

**Comment by chaoweihuang** [comment]
Hi @LWserenic ,

If you could provide the detailed error message maybe I could help you with that.

Chao-Wei

**Comment by LWserenic** [comment]
Hello @chaoweihuang ,

I found out that my dataset used 'labels' instead of 'label'. It's pretty stupid I know.
