### ISSUE TITLE
Conducting Custom Inference & Outputting Predicted Labels as Strings 

### ISSUE THREAD

**Issue by jatinvinkumar** [MiuLab/PLM-ICD#4]
Hi thank you for sharing this work! Could you please provide instructions on how I can convert the predicted label outputs to a readable string format?

**Comment by chaoweihuang** [comment]
Hi,

Thank you for your interest in our work!
Sure you can convert the predictions to a readable string format.
in `run_icd.py`, we first create a label_list after reading the codes file here: https://github.com/MiuLab/PLM-ICD/blob/master/src/run_icd.py#L255
Then at the end of the evaluation you can add something like this to get the codes in string format:
```
for preds in all_preds:
    pred_ids = np.where(np.array(preds) == 1)[0]
    label_strings = [label_list[id] for id in pred_ids]
```

Hope this answers your question.

Best,
Chao-Wei
