### ISSUE TITLE
Build fails on python 3.10

### ISSUE THREAD

**Issue by JosephSBoyle** [MiuLab/PLM-ICD#5]
Hi there, thanks for providing this repo.

When running `pip install -r requirements.txt` on win10, python version 3.10 the command errors with the following message:

![image](https://user-images.githubusercontent.com/48555120/227722499-8b01d6fc-0982-42de-8b16-7ae66069a4e1.png)

My interpretation of this is that the pinned versions in `requirements.txt` are not available for python 3.10,

The solution for me was to simply unpin all the versions as follows:

```
accelerate>=0.2.1
datasets>=1.6.0
jedi>=0.17.1
numpy>=1.19.5
pandas>=1.1.5
scikit-learn>=0.24.1
scipy>=1.5.4
tokenizers>=0.10.2
torch>=1.8.1
torchaudio>=0.8.1
torchvision>=0.9.1
tqdm>=4.49.0
transformers>=4.5.0
```
Which allows the install to finish.

**Comment by chaoweihuang** [comment]
Hi,

Thank you for your interest in our work!
The pinned versions in `requirements.txt` are for exact reproduction. I would assume most versions work exactly the same.
I'm glad you could sort it out! Although it's a bit weird that `1.19.5` actually presents in the versions list in your screenshot.
I'll modify the `README.md`.
Thank you!

Best,
Chao-Wei
